# get_api_keys.py
print("🔑 OTTIENI LE TUE API KEYS GRATUITE")
print("="*60)
print("\n1️⃣ ALPHA VANTAGE (500 chiamate/giorno):")
print("   Vai su: https://www.alphavantage.co/support/#api-key")
print("   Registrati e ricevi la chiave via email")
print("   Limiti: 5 chiamate/minuto, 500/giorno [citation:7]")
print("\n2️⃣ TWELVEDATA (800 chiamate/giorno):")
print("   Vai su: https://twelvedata.com/apikey")
print("   Registrati e copia la chiave")
print("   Limiti: 800 chiamate/giorno, 8/minuto [citation:4]")
print("\n" + "="*60)
print("Poi inseriscile in config.py:")
print('ALPHA_VANTAGE_KEY = "la_tua_chiave"')
print('TWELVEDATA_KEY = "la_tua_chiave"')